GREENHOUSE_COMPANIES = [
    "airbnb", "stripe", "notion", "figma", "robinhood", "coinbase", "brex",
    "gusto", "rippling", "lattice", "greenhouse", "lever", "workday", "zendesk",
    "hubspot", "intercom", "segment", "mixpanel", "amplitude", "datadog",
    "mongodb", "elastic", "confluent", "dbt-labs", "fivetran", "airbyte",
    "retool", "airtable", "coda", "linear", "vercel", "netlify", "supabase",
    "planetscale", "neon", "railway", "render", "fly", "modal", "anyscale",
    "scale-ai", "weights-biases", "huggingface", "cohere", "anthropic", "openai",
    "nvidia", "amd", "intel", "qualcomm", "arm", "apple", "google", "meta",
    "microsoft", "amazon", "netflix", "spotify", "uber", "lyft", "doordash",
    "instacart", "gopuff", "shipbob", "flexport", "shippo", "easypost",
    "plaid", "marqeta", "adyen", "checkout", "recurly", "chargebee", "paddle",
    "twilio", "sendgrid", "mailgun", "postmark", "klaviyo", "attentive",
    "salesforce", "servicenow", "workfront", "asana", "monday", "clickup",
    "notion", "coda", "quip", "dropbox", "box", "docusign", "hellosign",
    "zoom", "webex", "loom", "mmhmm", "miro", "lucid", "canva", "figma",
    "invision", "zeplin", "abstract", "framer", "webflow", "squarespace",
    "shopify", "bigcommerce", "woocommerce", "magento", "commercetools",
    "contentful", "sanity", "prismic", "strapi", "ghost", "wordpress",
    "cloudflare", "fastly", "akamai", "imperva", "crowdstrike", "sentinelone",
    "okta", "auth0", "ping-identity", "sailpoint", "cyberark", "beyond-trust",
    "pagerduty", "opsgenie", "victorops", "statuspage", "honeycomb", "lightstep",
    "new-relic", "dynatrace", "appdynamics", "splunk", "sumo-logic", "logdna",
    "hashicorp", "puppet", "chef", "ansible", "saltstack", "terraform",
    "docker", "rancher", "vmware", "nutanix", "pure-storage", "netapp",
    "snowflake", "databricks", "palantir", "domo", "looker", "tableau",
    "thoughtspot", "sigma", "mode", "hex", "deepnote", "observable",
    "census", "hightouch", "rudderstack", "segment", "mparticle", "lytics",
    "braze", "iterable", "customerio", "vero", "autopilot", "marketo",
    "drift", "intercom", "freshdesk", "zendesk", "kustomer", "gladly",
    "gong", "chorus", "salesloft", "outreach", "apollo", "zoominfo",
    "clearbit", "lusha", "hunter", "snov", "lemlist", "reply", "woodpecker",
    "greenhouse-io", "lever-co", "ashbyhq", "rippling", "bamboohr", "namely",
    "paychex", "adp", "paylocity", "paycom", "ceridian", "kronos",
    "workiva", "anaplan", "adaptive-insights", "planful", "vena", "prophix",
    "netsuite", "sap", "oracle", "infor", "epicor", "acumatica",
    "servicetitan", "jobber", "housecall-pro", "fieldedge", "successware",
    "veeva", "medidata", "iqvia", "oracle-health", "epic", "cerner",
    "doximity", "phreesia", "health-catalyst", "evolent", "privia",
    "procore", "autodesk", "bentley", "trimble", "hexagon", "topcon",
    "c3-ai", "datarobot", "h2o-ai", "abacus-ai", "samsara", "motive",
    "locus-robotics", "6-river-systems", "berkshire-grey", "symbotic",
    "nuro", "zoox", "aurora", "embark", "plus", "kodiak", "torc",
    "joby-aviation", "archer", "lilium", "wisk", "blade", "surf-air",
    "relativity-space", "rocket-lab", "planet", "spire", "hawkeye-360",
    "capella-space", "umbra", "iceye", "satellogic", "blacksky",
    "palantir", "anduril", "shield-ai", "skydio", "joby", "archer",
    "rivian", "lucid", "fisker", "canoo", "lordstown", "workhorse",
    "chargepoint", "blink", "evgo", "volta", "electrify-america",
    "sunrun", "sunnova", "sunpower", "enphase", "solaredge", "sma",
    "bloom-energy", "plug-power", "ballard", "fuelcell-energy",
    "recuritee", "teamtailor", "personio", "factorial", "kenjo", "hibob",
    "deel", "remote", "oyster", "papaya-global", "globalization-partners",
    "checkr", "sterling", "first-advantage", "hireright", "accurate",
    "indeed", "ziprecruiter", "glassdoor", "linkedin", "monster", "dice",
    "hired", "triplebyte", "codility", "hackerrank", "codesignal",
    "karat", "interviewing-io", "pramp", "exponent", "tryexponent",
    "robinhood", "chime", "dave", "current", "varo", "monzo", "revolut",
    "wise", "payoneer", "remitly", "worldremit", "xe", "oanda",
    "betterment", "wealthfront", "sofi", "lendingclub", "prosper",
    "affirm", "afterpay", "klarna", "sezzle", "zip", "perpay",
    "blend", "better", "loansnap", "beeline", "homepoint", "pennymac",
    "lemonade", "hippo", "kin", "branch", "metromile", "root",
    "oscar-health", "bright-health", "clover-health", "alignment",
    "hims", "ro", "cerebral", "done", "ahead", "brightside",
    "devoted-health", "cityblock", "oak-street", "iora", "carbon-health",
    "one-medical", "crossover-health", "premise-health", "marathon-health",
    "noom", "vida", "omada", "livongo", "teladoc", "mdlive", "amwell",
    "calm", "headspace", "talkspace", "betterhelp", "brightquest",
    "duolingo", "coursera", "udemy", "skillshare", "masterclass",
    "chegg", "chegg-skills", "pluralsight", "oreilly", "linkedin-learning",
    "roblox", "unity", "epic-games", "ea", "activision", "ubisoft",
    "zynga", "kabam", "glu", "jam-city", "scopely", "playstudios",
    "niantic", "secondspectrum", "statsperform", "sportradar", "genius-sports",
    "draftking", "fanduel", "pointsbet", "betmgm", "caesars", "wynn"
]

LEVER_COMPANIES = [
    "netflix", "twitter", "square", "carta", "faire", "dutchie",
    "checkr", "chime", "opendoor", "convoy", "flexport", "project44",
    "stytch", "supabase", "temporal", "buf", "dbtlabs", "hightouch",
    "census", "metabase", "preset", "airbyte", "meltano", "dagster",
    "prefect", "astronomer", "great-expectations", "monte-carlo",
    "accenture", "mckinsey", "bain", "bcg", "deloitte", "pwc", "kpmg",
    "ey", "booz-allen", "leidos", "saic", "caci", "maximus", "peraton",
    "mitre", "rand", "sri", "ida", "cna", "urban-institute",
    "nerdwallet", "creditkarma", "experian", "equifax", "transunion",
    "dun-bradstreet", "verisk", "moody", "sp-global", "msci", "factset",
    "bloomberg", "refinitiv", "ihs-markit", "wood-mackenzie", "rystad",
    "pagerduty", "victorops", "alertmanager", "grafana", "prometheus",
    "influxdata", "timescale", "questdb", "clickhouse", "pinot",
    "druid", "imply", "startree", "rockset", "materialize", "ksql",
    "confluent", "redpanda", "memphis", "nats", "pulsar", "rabbitmq"
]

WORKABLE_COMPANIES = [
    "typeform", "hotjar", "semrush", "ahrefs", "moz", "brightedge",
    "conductor", "botify", "deepcrawl", "oncrawl", "sitebulb", "screaming-frog",
    "mention", "brandwatch", "talkwalker", "sprinklr", "hootsuite", "buffer",
    "later", "planoly", "preview", "unum", "tailwind", "smarterqueue",
    "sendible", "agora-pulse", "socialbakers", "quintly", "socialinsider",
    "iconosquare", "phlanx", "upfluence", "grin", "aspire", "creator-iq",
    "traackr", "mavrck", "klear", "heepsy", "modash", "hypeauditor",
    "bazaarvoice", "yotpo", "okendo", "stamped", "junip", "loox",
    "trustpilot", "reviews-io", "feefo", "reevoo", "shopper-approved",
    "podium", "birdeye", "grade-us", "review-trackers", "reputation",
    "uberall", "yext", "chatmeter", "synup", "brightlocal", "whitespark",
    "moz-local", "advice-local", "localbusiness", "rio-seo", "brandify"
]

def get_all_companies():
    return {
        "greenhouse": GREENHOUSE_COMPANIES,
        "lever": LEVER_COMPANIES,
        "workable": WORKABLE_COMPANIES
    }
